name: playerCI
on:
  push:
    branches: [ dev ]
jobs:
    Docker:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./aspnet
          file: ./aspnet/src/Management.HttpApi.Host/Dockerfile
          push: true
          pull: true
          tags: justforlrn/hoaml:lastest
      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
    PullAndRunDockerInServer:      
      needs: Docker
      runs-on: ubuntu-latest
      steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} #hostname of server
          username: ${{ secrets.SSH_USER }} #username login to server
          password: ${{ secrets.SSH_PASSWORD }} #password login to server
          port: 22 #port of server - often port is 22
          script: | # run with multiple script
            cd ~/www/app/hoaml
            git checkout dev
            git pull
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker system prune -a --force
            docker-compose up -d
